push = require 'lib/push'
Class = require 'lib/class'
require 'lib/util'
require 'lib/math'
require 'lib/table'
require 'lib/tilemath'

require 'src/constants'
require 'src/assets/dependencies'
require 'src/states/dependencies'