push = require 'lib/push'
Class = require 'lib/class'
require 'lib/util'
require 'lib/math'
require 'lib/table'
require 'lib/tilemath'
require 'lib/Coordinates'
require 'src/assets/settings/Settings'

require 'src/constants'
require 'src/assets/dependencies'
require 'src/states/dependencies'