MAP_WIDTH = 1920
MAP_HEIGHT = 1020

GRAVITY = 8

-- minimum size
TILE_SIZE = 10

-- bullets
BULLET_WIDTH = 10
BULLET_HEIGHT = 10
BULLET_SPEED = 1000
BULLET_DAMAGE = 5

-- interface
BUTTON_SCALE = 0.75
BAR_SIZE = 50 * BUTTON_SCALE
BUTTON_SIZE = 40 * BUTTON_SCALE

DEBUG_MODE = true